version: "3.9"

services:
  server:
    container_name: prakticum-server
    image: cr.yandex/*****/sekta:server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: 3001
    restart: always
    hostname: prakticum-server
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 3001
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      CLIENT_PATH: /app
    networks:
      - default-network

  postgres:
    container_name: postgres
    image: cr.yandex/******/sekta:postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default-network

  nginx:
    image: cr.yandex/*****/sekta:nginx
    depends_on:
      - server
      - postgres
    restart: always
    volumes:
      - /home/sekta/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/sekta/nginx/cert.pem:/etc/nginx/ssl/cert.pem
      - /home/sekta/nginx/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - 80:80
      - 443:443
    networks:
      - default-network

networks:
  default-network:
    driver: bridge