export const GAME_OPTIONS = {
  // настройки отображения
  GAME_MIN_FPS: 25,
  GAME_MAIN_FPS: 60,
  CANVAS_WIDTH: 1280,
  CANVAS_HEIGHT: 720,
  CANVAS_OFFSET: 0.15,
  FLOOR_HEIGHT: 75,
  // настройки физики игры
  GRAVITY_VALUE: 30,
  FRICTION_FORCE: 0.05,
  SPEED_STEP: 0.03,
  // настройки персонажа
  PLAYER_WIDTH: 50,
  PLAYER_HEIGHT: 100,
  PLAYER_SPEED: 5,
  PLAYER_LEFT_OFFSET: 50,
  PLAYER_JUMP_MULTIPLIER: 2.2,
  PLAYER_JUMP_DURATION: 200,
  PLAYER_JUMP_BLOCKTIME: 1500,
  // настройки ловушек
  TRAP_WIDTH: 20,
  TRAP_HEIGHT: 20,
  TRAP_SPEED: 200,
  TRAP_TIME: 3000,
  // настройки огненного дождя
  FIREBALL_WIDTH: 20,
  FIREBALL_HEIGHT: 20,
  FIREBALL_SPEED_MIN: 100,
  FIREBALL_SPEED_MAX: 105,
  // настройки фона игры
  BACKGROUND_LANDSCAPE_SPEED: 75,
  BACKGROUND_ROAD_SPEED: 100,
  BACKGROUND_SKY_SPEED: 50,
  BACKGROUND_TIME: 20000,
  // настройки звукового сопровождения
  MASTER_SOUND_VOLUME: 1.0,
  BACKGROUND_SOUND_VOLUME: 0.5,
}
